name: CI Pipeline

on:
  push:


jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '>=1.24.0'
    - uses: extractions/setup-just@v1

    - name: Test
      run: just test-cover

    - name: Upload coverage
      uses: codecov/codecov-action@v5
      with:
        fail_ci_if_error: true
        files: .coverage
        token: ${{ secrets.CODECOV_TOKEN }}
